[versions]

# Stuff
kotlin = "2.4.0"
cloche = "0.19.12"

# Minecraft
minecraft = "1.21.1"

# Common Dependencies
kritter = "2.0.0-alpha.50"
kotlinx-serialization = "1.8.0"
kotlinx-coroutines = "1.10.1"
parchment = "2024.11.17"
devauth = "1.2.1"
rei = "16.0.799"
emi = "1.1.24+1.21.1"
jei = "19.27.0.343-neoforge"
mixin_extras = "0.5.3"
mixin = "0.8.5"
flywheel = "1.0.6"
cynosure = "1.0.0.35"
ponder = "1.0.69"
kubejs = "2101.7.2-build.368"
estrogen = "6.0.0+1.21.1-alpha.2"
csr = "0.0.9"
rlib = "3.0.12"
# Forge Only Dependencies
registrate_forge = "MC1.21-1.3.0+67"
neoforge = "21.1.233"
curios = "9.5.1+1.21.1"
create_forge = "6.0.11-295"
kff = "5.12.0"

[libraries]

# Common Dependencies
#kubejs = {group = "dev.latvian.mods", name = "kubejs", version.ref ="kubejs"}
estrogen = { group = "dev.mayaqq", name = "estrogen", version.ref = "estrogen" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
cynosure = { module = "dev.mayaqq.cynosure:cynosure", version.ref = "cynosure" }
forge-registrate = {group = "com.tterrag.registrate", name = "Registrate", version.ref="registrate_forge"}
forge-ponder  = {group = "net.createmod.ponder", name = "Ponder-NeoForge-1.21.1", version.ref = "ponder"}
forge-kotlin = { module = "thedarkcolour:kotlinforforge", version.ref = "kff" }
forge-create = { group = "com.simibubi.create" ,name = "create-1.21.1", version.ref = "create_forge" }
forge-csr = { module = "earth.terrarium.common_storage_lib:common-storage-lib-neoforge-1.21.1", version.ref = "csr" }
forge-rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21", version.ref = "rlib" }
forge-emi = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
forge-jei = { module = "maven.modrinth:jei", version.ref = "jei" }
forge-rei = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei" }
forge-curios = { module = "top.theillusivec4.curios:curios-forge", version.ref = "curios" }
forge-mixinExtras = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixin_extras" }
forge-devauth = { module = "me.djtheredstoner:DevAuth-forge-latest", version.ref = "devauth" }
forge-kritter = { module = "invoke.kitty.kritter:kritter-1.21.1-neoforge", version.ref = "kritter" }
forge-kritter-lang = { module = "invoke.kitty.kritter:kritter-1.21.1-neoforge-lang", version.ref = "kritter" }
forge-flywheel-api = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
forge-flywheel = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
# forge-cynosure = { module = "dev.mayaqq.cynosure:cynosure-forge", version.ref = "cynosure" }
forge-kubejs = {group = "dev.latvian.mods", name = "kubejs-neoforge", version.ref ="kubejs"}

[plugins]
cloche = { id = "earth.terrarium.cloche", version.ref = "cloche" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }